version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d finance_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=finance_db
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - finance-network
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL...' &&
        sleep 10 &&
        go run main.go
      "
    restart: on-failure

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - finance-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  finance-network:
    driver: bridge