services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-mysecretpassword}
      - DB_NAME=${DB_NAME:-mydatabase}
      - JWT_SECRET=${JWT_SECRET:-mysecretpasswordjwt}
    depends_on:
      - postgres
    networks:
      - finance-app-network

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-mydatabase}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-mysecretpassword}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - finance-app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - finance-app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  finance-app-network:
    driver: bridge

volumes:
  postgres-data: