services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-mysecretpassword}
      - DB_NAME=${DB_NAME:-mydatabase}
    depends_on:
      - postgres
    networks:
      - finance-app-network

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-mydatabase}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-mysecretpassword}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - finance-app-network

networks:
  finance-app-network:
    driver: bridge

volumes:
  postgres-data: